# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eligibility.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='eligibility.proto',
  package='com.voting.eligibility',
  syntax='proto3',
  serialized_pb=_b('\n\x11\x65ligibility.proto\x12\x16\x63om.voting.eligibility\"?\n\x07\x44\x65tails\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0bnationality\x18\x02 \x01(\t\x12\x11\n\tadhaar_id\x18\x03 \x01(\x05\"\x18\n\x06Status\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x12\n\x03\x41ge\x12\x0b\n\x03\x61ge\x18\x01 \x01(\x05\"4\n\x0b\x45ligibility\x12\x10\n\x08\x65ligible\x18\x01 \x01(\t\x12\x13\n\x0bnotEligible\x18\x02 \x01(\t2\xb2\x01\n\x11VotingEligibility\x12O\n\ngetDetails\x12\x1f.com.voting.eligibility.Details\x1a\x1e.com.voting.eligibility.Status\"\x00\x12L\n\x06getAge\x12\x1b.com.voting.eligibility.Age\x1a#.com.voting.eligibility.Eligibility\"\x00\x62\x06proto3')
)




_DETAILS = _descriptor.Descriptor(
  name='Details',
  full_name='com.voting.eligibility.Details',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='com.voting.eligibility.Details.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nationality', full_name='com.voting.eligibility.Details.nationality', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='adhaar_id', full_name='com.voting.eligibility.Details.adhaar_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=108,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='com.voting.eligibility.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='com.voting.eligibility.Status.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=134,
)


_AGE = _descriptor.Descriptor(
  name='Age',
  full_name='com.voting.eligibility.Age',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='age', full_name='com.voting.eligibility.Age.age', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=154,
)


_ELIGIBILITY = _descriptor.Descriptor(
  name='Eligibility',
  full_name='com.voting.eligibility.Eligibility',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='eligible', full_name='com.voting.eligibility.Eligibility.eligible', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='notEligible', full_name='com.voting.eligibility.Eligibility.notEligible', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=208,
)

DESCRIPTOR.message_types_by_name['Details'] = _DETAILS
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.message_types_by_name['Age'] = _AGE
DESCRIPTOR.message_types_by_name['Eligibility'] = _ELIGIBILITY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Details = _reflection.GeneratedProtocolMessageType('Details', (_message.Message,), dict(
  DESCRIPTOR = _DETAILS,
  __module__ = 'eligibility_pb2'
  # @@protoc_insertion_point(class_scope:com.voting.eligibility.Details)
  ))
_sym_db.RegisterMessage(Details)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), dict(
  DESCRIPTOR = _STATUS,
  __module__ = 'eligibility_pb2'
  # @@protoc_insertion_point(class_scope:com.voting.eligibility.Status)
  ))
_sym_db.RegisterMessage(Status)

Age = _reflection.GeneratedProtocolMessageType('Age', (_message.Message,), dict(
  DESCRIPTOR = _AGE,
  __module__ = 'eligibility_pb2'
  # @@protoc_insertion_point(class_scope:com.voting.eligibility.Age)
  ))
_sym_db.RegisterMessage(Age)

Eligibility = _reflection.GeneratedProtocolMessageType('Eligibility', (_message.Message,), dict(
  DESCRIPTOR = _ELIGIBILITY,
  __module__ = 'eligibility_pb2'
  # @@protoc_insertion_point(class_scope:com.voting.eligibility.Eligibility)
  ))
_sym_db.RegisterMessage(Eligibility)



_VOTINGELIGIBILITY = _descriptor.ServiceDescriptor(
  name='VotingEligibility',
  full_name='com.voting.eligibility.VotingEligibility',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=211,
  serialized_end=389,
  methods=[
  _descriptor.MethodDescriptor(
    name='getDetails',
    full_name='com.voting.eligibility.VotingEligibility.getDetails',
    index=0,
    containing_service=None,
    input_type=_DETAILS,
    output_type=_STATUS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getAge',
    full_name='com.voting.eligibility.VotingEligibility.getAge',
    index=1,
    containing_service=None,
    input_type=_AGE,
    output_type=_ELIGIBILITY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_VOTINGELIGIBILITY)

DESCRIPTOR.services_by_name['VotingEligibility'] = _VOTINGELIGIBILITY

# @@protoc_insertion_point(module_scope)
