# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import eligibility_pb2 as eligibility__pb2


class VotingEligibilityStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getDetails = channel.unary_unary(
        '/com.voting.eligibility.VotingEligibility/getDetails',
        request_serializer=eligibility__pb2.Details.SerializeToString,
        response_deserializer=eligibility__pb2.Status.FromString,
        )
    self.getAge = channel.unary_unary(
        '/com.voting.eligibility.VotingEligibility/getAge',
        request_serializer=eligibility__pb2.Age.SerializeToString,
        response_deserializer=eligibility__pb2.Eligibility.FromString,
        )


class VotingEligibilityServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getDetails(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getAge(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_VotingEligibilityServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getDetails': grpc.unary_unary_rpc_method_handler(
          servicer.getDetails,
          request_deserializer=eligibility__pb2.Details.FromString,
          response_serializer=eligibility__pb2.Status.SerializeToString,
      ),
      'getAge': grpc.unary_unary_rpc_method_handler(
          servicer.getAge,
          request_deserializer=eligibility__pb2.Age.FromString,
          response_serializer=eligibility__pb2.Eligibility.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'com.voting.eligibility.VotingEligibility', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
